stages:
- name: update
  if: branch = master AND type = cron
- name: version
  if: branch = master
env:
  global:
  - GIT_USER_NAME=vue-cli-locales-bot
  - GIT_USER_EMAIL=vue-cli-locales-bot@caugner.de
matrix:
  include:
  - stage: update
    language: python
    script: |
      if [ -n "$GH_TOKEN" -a -n "$TX_TOKEN" ]; then
        git checkout "$TRAVIS_BRANCH"
        tx pull --parallel -asf
        git add .
        git config --local user.name "$GIT_USER_NAME"
        git config --local user.email "$GIT_USER_EMAIL"
        git commit -m "[tx-bot] updated from transifex"
        git push -f -q https://vue-cli-locales-bot:$GH_TOKEN@github.com/caugner/vue-cli-locales "$TRAVIS_BRANCH" &> /dev/null
      fi
  - stage: version
    language: node_js
    node_js:
    - node
    script: |
      UPSTREAM=$(npm view @vue/cli version)
      ORIGIN=$(npm view vue-cli-locales version)
      if [ "$UPSTREAM" != "$ORIGIN" ]; then
        git checkout "$TRAVIS_BRANCH"
        git config --local user.name "$GIT_USER_NAME"
        git config --local user.email "$GIT_USER_EMAIL"
        export TRAVIS_TAG=$(npm version "$UPSTREAM")
        git push -f -q --tags https://vue-cli-locales-bot:$GH_TOKEN@github.com/caugner/vue-cli-locales "$TRAVIS_BRANCH" &> /dev/null
      fi
deploy:
  provider: npm
  email: node@caugner.de
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    repo: caugner/vue-cli-locales
